FROM python:3.11-slim

WORKDIR /app

COPY requirements_train.txt .

RUN pip install -r requirements_train.txt

COPY model_preprocessing.py .
COPY model_preparation.py .

CMD ["sh", "-c", "python model_preprocessing.py && python model_preparation.py"]